
int GetRobotActualJointPosition(int id, double *j0, double *j1, double *j2, double *j3, double *j4, double *j5, double *j6, double *j7);
int GetRobotToolPosition(int id, double *x, double *y, double *z, double *roll, double *grasp);
int GetRobotRCMPosition(int id, double *x, double *y, double *z);
void GetTimerCount(unsigned long *cnt);
void GetRobotNetworkCommunication(int id, int *robotConnected, unsigned long *txcnt, unsigned long *rxcnt);
void GetArmHomingStatus(int id, unsigned char *homingDone);
void GetToolHomingStatus(int id, unsigned char *homingDone);
void GetXYZStageHomingStatus(int id, unsigned char *homingDone);
void GetArmActualPower(int id, unsigned char *power);
void GetXYZStageActualPower(int id, unsigned char *power);
void GetRobotStatus(int id, int *robot_status);
void GetRobotErrors(int id, int *robot_error);
void GetToolInsertionLength(int id, double *insertionLength);
int CommandHomingArmJoints(int id);
int CommandHomingToolJoints(int id);
int CommandHomingXYZStage(int id);;
int CommandToolInsertion(int id, double insertionLength, double speed);
int CommandToolRetraction(int id);
int CommandSetToolType(int id, int toolType);
int CommandRobotJointPosition(int id, double j0, double j1, double j2, double j3, double j4, double j5, double j6, double j7);
int CommandRobotToolPosition(int id, double x, double y, double z, double roll, double grasp);
int CommandRobotRCMPosition(int id, double x, double y, double z);
int CommandRobotArmPowerOnOff(int id, int OnOff);
int CommandXYZStagePowerOnOff(int id, int OnOff);
int CommandSetToolInsertionOffset(int id, double offset);
int CommandJointControlMode(int id);
int CommandXYZControlMode(int id);
int CommandRobotRunPause(int id, int runpause);
int CommandRobotEStop(int id, int estop);
void CommandNone(int id);
void UpdateRobotData(int id);
void OpenRobot(int id);
void CloseRobot(int id);
void KillRobotControlProcess(int id);
