function [r1, r2, r3, r4, u1, u2, u3, u4, y1, y2, y3, y4] = ImportExpData(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [R1, R2, R3, R4, U1, U2, U3, U4, Y1, Y2, Y3, Y4] =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as column vectors.
%
%  [R1, R2, R3, R4, U1, U2, U3, U4, Y1, Y2, Y3, Y4] = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [r1, r2, r3, r4, u1, u2, u3, u4, y1, y2, y3, y4] = importfile("D:\IRISS Exp\2021-04-15 ILC Raster 20s Circle Vel Prof\Iter4_Physical.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Apr-2021 17:09:13

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["r1", "r2", "r3", "r4", "u1", "u2", "u3", "u4", "y1", "y2", "y3", "y4"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
r1 = tbl.r1;
r2 = tbl.r2;
r3 = tbl.r3;
r4 = tbl.r4;
u1 = tbl.u1;
u2 = tbl.u2;
u3 = tbl.u3;
u4 = tbl.u4;
y1 = tbl.y1;
y2 = tbl.y2;
y3 = tbl.y3;
y4 = tbl.y4;
end