function [t, Vcmd, Pirr, Pvac, Pac, Pvit] = loadIopData(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [T, VCMD, PIRR, PVAC, PAC, PVIT] = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as column vectors.
%
%  [T, VCMD, PIRR, PVAC, PAC, PVIT] = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [t, Vcmd, Pirr, Pvac, Pac, Pvit] = importfile("C:\Users\IRISS-PC\Desktop\2021-02-24 IOP PID Ctrl\KevData2.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Feb-2021 13:29:59

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["t", "Vcmd", "Pirr", "Pvac", "Pac", "Pvit"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
t = tbl.t;
Vcmd = tbl.Vcmd;
Pirr = tbl.Pirr;
Pvac = tbl.Pvac;
Pac = tbl.Pac;
Pvit = tbl.Pvit;
end