function [t, Pdes, Vcmd, Pirr, Pvac, Pac, Pvit] = loadIopData_rev1(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [T1, PDES, VCMD1, PIRR1, PVAC1, PAC1, PVIT1] = IMPORTFILE(FILENAME)
%  reads data from text file FILENAME for the default selection.
%  Returns the data as column vectors.
%
%  [T1, PDES, VCMD1, PIRR1, PVAC1, PAC1, PVIT1] = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [t1, Pdes, Vcmd1, Pirr1, Pvac1, Pac1, Pvit1] = importfile("C:\Users\IRISS-PC\Desktop\2021-02-24 IOP PID Ctrl\KevData4.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Feb-2021 17:27:14

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["t1", "Pdes", "Vcmd1", "Pirr1", "Pvac1", "Pac1", "Pvit1"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
t = tbl.t1;
Pdes = tbl.Pdes;
Vcmd = tbl.Vcmd1;
Pirr = tbl.Pirr1;
Pvac = tbl.Pvac1;
Pac = tbl.Pac1;
Pvit = tbl.Pvit1;
end